server:
  port: 8089
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/community?useUnicode=true&characterEncoding=utf-8&serverTimeZone=Hongkong
    username: root
    password: root
    druid:
      max-active: 15
      min-idle: 5

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true    # 开启驼峰命名转换
pagehelper:
  helper-dialect: mysql # 指定数据库类型
  reasonable: true
  params: count=countSql
  support-methods-arguments: true

logging:
  level:
    com:
      jia:
        dao: debug
  file: D:/log/data/newcoder.log